name: zekryptofolio
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  injectable: ^2.5.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  stacked: ^3.4.3
  stacked_hooks: ^0.2.4
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  bloc_test: ^9.1.3
  cached_network_image: ^3.2.3
  dio: ^5.1.2
  flutter_animate: ^4.2.0
  flutter_mobx: ^2.0.6+5
  flutter_riverpod: ^2.3.6
  get_it_mixin: ^4.2.0
  google_fonts: ^6.2.1
  material_color_utilities: ^0.11.1
  stream_transform: ^2.1.0
  mobx: ^2.2.1
  meta: ^1.9.1

  intl: ^0.19.0
  flutter_speed_dial: ^6.2.0
  events_emitter: ^0.5.2
  sqflite_common_ffi: ^2.2.5
  currency_picker: ^2.0.16
  material_symbols_icons: ^4.2741.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  file_picker: ^8.0.0+1
  path: ^1.9.0

  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.7
  fl_chart: ^0.69.0
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.8
  get_it: ^7.7.0
  hive_flutter: ^1.1.0
  http: ^1.2.2
  salomon_bottom_bar: ^3.3.2
  shimmer: ^3.0.0
  coingecko_api: ^2.0.1

  google_sign_in: ^6.2.1
  crypto: ^3.0.6 
  font_awesome_flutter: ^10.7.0
  rxdart: ^0.27.7
  json_annotation: ^4.9.0
  particles_flutter: ^0.1.1
  firebase_app_check: ^0.3.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.3
  mockingjay: ^0.5.0
  mobx_codegen: ^2.1.1

   # Generators:
  json_serializable: ^6.2.0
  drift_dev: ^2.21.1
  slang_build_runner: ^3.18.0 # To regenerate the translations run 'dart run slang'
  copy_with_extension_gen: ^5.0.4

  auto_route_generator: ^9.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icon.jpg
    - assets/Background.jpg
    - assets/Background_base.jpg

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"