name: zekryptofolio
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2

  fl_chart: ^0.69.0
  http: ^1.2.2

  font_awesome_flutter: ^10.7.0

  google_sign_in: ^6.2.1
  particles_flutter: ^0.1.1
  supabase_flutter: ^2.8.0

  flutter_svg: ^2.0.5
  spider: ^4.2.2

  random_color: ^1.0.6-nullsafety
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icon.jpg
    - assets/Background.jpg
    - assets/Background_base.jpg
    - assets/vectors/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"